[unstable]
# this allows us to use the core rust stuff, such as Result, Option, panic, etc.
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins", "alloc"]

[build]
target = "x86_64-comet_os.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"
