name: Testing OS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  base:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Install QEMU
        uses: docker/setup-qemu-action@v2.1.0
      
      - run: rustup override set nightly
      - run: rustup component add rust-src
      - run: rustup component add llvm-tools-preview
      - run: cargo install bootimage
      - run: cargo bootimage
      
      - run: cargo build --verbose
      - run: cargo test --verbose
